apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"labels":{"app.kubernetes.io/component":"awx","app.kubernetes.io/managed-by":"awx-operator","app.kubernetes.io/name":"awx-coopaname","app.kubernetes.io/operator-version":"","app.kubernetes.io/part-of":"awx-coopaname","app.kubernetes.io/version":"19.4.0"},"name":"awx-coopaname","namespace":"awx"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/component":"awx","app.kubernetes.io/managed-by":"awx-operator","app.kubernetes.io/name":"awx-coopaname"}},"template":{"metadata":{"labels":{"app.kubernetes.io/component":"awx","app.kubernetes.io/managed-by":"awx-operator","app.kubernetes.io/name":"awx-coopaname","app.kubernetes.io/part-of":"awx-coopaname","app.kubernetes.io/version":"19.4.0"}},"spec":{"containers":[{"args":["redis-server","/etc/redis.conf"],"image":"docker.io/redis:latest","imagePullPolicy":"IfNotPresent","name":"redis","volumeMounts":[{"mountPath":"/etc/redis.conf","name":"awx-coopaname-redis-config","readOnly":true,"subPath":"redis.conf"},{"mountPath":"/var/run/redis","name":"awx-coopaname-redis-socket"},{"mountPath":"/data","name":"awx-coopaname-redis-data"}]},{"env":[{"name":"MY_POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"quay.io/ansible/awx:19.4.0","imagePullPolicy":"IfNotPresent","name":"awx-coopaname-web","ports":[{"containerPort":8052}],"resources":{"requests":{"cpu":"1000m","memory":"2Gi"}},"volumeMounts":[{"mountPath":"/etc/tower/conf.d/execution_environments.py","name":"awx-coopaname-application-credentials","readOnly":true,"subPath":"execution_environments.py"},{"mountPath":"/etc/tower/conf.d/credentials.py","name":"awx-coopaname-application-credentials","readOnly":true,"subPath":"credentials.py"},{"mountPath":"/etc/tower/conf.d/ldap.py","name":"awx-coopaname-application-credentials","readOnly":true,"subPath":"ldap.py"},{"mountPath":"/etc/tower/SECRET_KEY","name":"awx-coopaname-secret-key","readOnly":true,"subPath":"SECRET_KEY"},{"mountPath":"/etc/tower/settings.py","name":"awx-coopaname-settings","readOnly":true,"subPath":"settings.py"},{"mountPath":"/etc/nginx/nginx.conf","name":"awx-coopaname-nginx-conf","readOnly":true,"subPath":"nginx.conf"},{"mountPath":"/var/run/redis","name":"awx-coopaname-redis-socket"},{"mountPath":"/var/run/supervisor","name":"supervisor-socket"},{"mountPath":"/var/run/awx-rsyslog","name":"rsyslog-socket"},{"mountPath":"/var/lib/awx/rsyslog","name":"rsyslog-dir"},{"mountPath":"/var/lib/awx/projects","name":"awx-coopaname-projects"}]},{"args":["/usr/bin/launch_awx_task.sh"],"env":[{"name":"SUPERVISOR_WEB_CONFIG_PATH","value":"/etc/supervisord.conf"},{"name":"AWX_SKIP_MIGRATIONS","value":"1"},{"name":"MY_POD_UID","valueFrom":{"fieldRef":{"fieldPath":"metadata.uid"}}},{"name":"MY_POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}},{"name":"MY_POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"quay.io/ansible/awx:19.4.0","imagePullPolicy":"IfNotPresent","name":"awx-coopaname-task","resources":{"requests":{"cpu":"500m","memory":"1Gi"}},"volumeMounts":[{"mountPath":"/etc/tower/conf.d/execution_environments.py","name":"awx-coopaname-application-credentials","readOnly":true,"subPath":"execution_environments.py"},{"mountPath":"/etc/tower/conf.d/credentials.py","name":"awx-coopaname-application-credentials","readOnly":true,"subPath":"credentials.py"},{"mountPath":"/etc/tower/conf.d/ldap.py","name":"awx-coopaname-application-credentials","readOnly":true,"subPath":"ldap.py"},{"mountPath":"/etc/tower/SECRET_KEY","name":"awx-coopaname-secret-key","readOnly":true,"subPath":"SECRET_KEY"},{"mountPath":"/etc/tower/settings.py","name":"awx-coopaname-settings","readOnly":true,"subPath":"settings.py"},{"mountPath":"/var/run/redis","name":"awx-coopaname-redis-socket"},{"mountPath":"/var/run/supervisor","name":"supervisor-socket"},{"mountPath":"/var/run/awx-rsyslog","name":"rsyslog-socket"},{"mountPath":"/var/lib/awx/rsyslog","name":"rsyslog-dir"},{"mountPath":"/etc/receptor/receptor.conf","name":"awx-coopaname-receptor-config","readOnly":true,"subPath":"receptor.conf"},{"mountPath":"/var/run/receptor","name":"receptor-socket"},{"mountPath":"/var/lib/awx/projects","name":"awx-coopaname-projects"}]},{"args":["receptor","--config","/etc/receptor/receptor.conf"],"env":null,"image":"quay.io/ansible/awx-ee:latest","imagePullPolicy":"IfNotPresent","name":"awx-coopaname-ee","resources":{"requests":{"cpu":"500m","memory":"1Gi"}},"volumeMounts":[{"mountPath":"/etc/receptor/receptor.conf","name":"awx-coopaname-receptor-config","readOnly":true,"subPath":"receptor.conf"},{"mountPath":"/var/run/receptor","name":"receptor-socket"},{"mountPath":"/var/lib/awx/projects","name":"awx-coopaname-projects"}]}],"serviceAccountName":"awx-coopaname","volumes":[{"name":"awx-coopaname-application-credentials","secret":{"items":[{"key":"credentials.py","path":"credentials.py"},{"key":"ldap.py","path":"ldap.py"},{"key":"execution_environments.py","path":"execution_environments.py"}],"secretName":"awx-coopaname-app-credentials"}},{"name":"awx-coopaname-secret-key","secret":{"items":[{"key":"secret_key","path":"SECRET_KEY"}],"secretName":"awx-coopaname-secret-key"}},{"configMap":{"items":[{"key":"settings","path":"settings.py"}],"name":"awx-coopaname-awx-configmap"},"name":"awx-coopaname-settings"},{"configMap":{"items":[{"key":"nginx_conf","path":"nginx.conf"}],"name":"awx-coopaname-awx-configmap"},"name":"awx-coopaname-nginx-conf"},{"configMap":{"items":[{"key":"redis_conf","path":"redis.conf"}],"name":"awx-coopaname-awx-configmap"},"name":"awx-coopaname-redis-config"},{"emptyDir":{},"name":"awx-coopaname-redis-socket"},{"emptyDir":{},"name":"awx-coopaname-redis-data"},{"emptyDir":{},"name":"supervisor-socket"},{"emptyDir":{},"name":"rsyslog-socket"},{"emptyDir":{},"name":"receptor-socket"},{"emptyDir":{},"name":"rsyslog-dir"},{"configMap":{"items":[{"key":"receptor_conf","path":"receptor.conf"}],"name":"awx-coopaname-awx-configmap"},"name":"awx-coopaname-receptor-config"},{"emptyDir":{},"name":"awx-coopaname-projects"}]}}}}'
  creationTimestamp: "2021-10-24T07:16:34Z"
  generation: 2
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx-coopaname
    app.kubernetes.io/operator-version: ""
    app.kubernetes.io/part-of: awx-coopaname
    app.kubernetes.io/version: 19.4.0
  name: awx-coopaname
  namespace: awx
  ownerReferences:
  - apiVersion: awx.ansible.com/v1beta1
    kind: AWX
    name: awx-coopaname
    uid: 381939e9-3824-43f8-a6f4-0fc4cfaf0c4d
  resourceVersion: "11036"
  uid: a5874aa4-1394-4b2c-b3b4-4ea42a80a52c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: awx
      app.kubernetes.io/managed-by: awx-operator
      app.kubernetes.io/name: awx-coopaname
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: awx
        app.kubernetes.io/managed-by: awx-operator
        app.kubernetes.io/name: awx-coopaname
        app.kubernetes.io/part-of: awx-coopaname
        app.kubernetes.io/version: 19.4.0
    spec:
      containers:
      - args:
        - redis-server
        - /etc/redis.conf
        image: docker.io/redis:latest
        imagePullPolicy: IfNotPresent
        name: redis
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/redis.conf
          name: awx-coopaname-redis-config
          readOnly: true
          subPath: redis.conf
        - mountPath: /var/run/redis
          name: awx-coopaname-redis-socket
        - mountPath: /data
          name: awx-coopaname-redis-data
      - env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/ansible/awx:19.4.0
        imagePullPolicy: IfNotPresent
        name: awx-coopaname-web
        ports:
        - containerPort: 8052
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tower/conf.d/execution_environments.py
          name: awx-coopaname-application-credentials
          readOnly: true
          subPath: execution_environments.py
        - mountPath: /etc/tower/conf.d/credentials.py
          name: awx-coopaname-application-credentials
          readOnly: true
          subPath: credentials.py
        - mountPath: /etc/tower/conf.d/ldap.py
          name: awx-coopaname-application-credentials
          readOnly: true
          subPath: ldap.py
        - mountPath: /etc/tower/SECRET_KEY
          name: awx-coopaname-secret-key
          readOnly: true
          subPath: SECRET_KEY
        - mountPath: /etc/tower/settings.py
          name: awx-coopaname-settings
          readOnly: true
          subPath: settings.py
        - mountPath: /etc/nginx/nginx.conf
          name: awx-coopaname-nginx-conf
          readOnly: true
          subPath: nginx.conf
        - mountPath: /var/run/redis
          name: awx-coopaname-redis-socket
        - mountPath: /var/run/supervisor
          name: supervisor-socket
        - mountPath: /var/run/awx-rsyslog
          name: rsyslog-socket
        - mountPath: /var/lib/awx/rsyslog
          name: rsyslog-dir
        - mountPath: /var/lib/awx/projects
          name: awx-coopaname-projects
      - args:
        - /usr/bin/launch_awx_task.sh
        env:
        - name: SUPERVISOR_WEB_CONFIG_PATH
          value: /etc/supervisord.conf
        - name: AWX_SKIP_MIGRATIONS
          value: "1"
        - name: MY_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/ansible/awx:19.4.0
        imagePullPolicy: IfNotPresent
        name: awx-coopaname-task
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tower/conf.d/execution_environments.py
          name: awx-coopaname-application-credentials
          readOnly: true
          subPath: execution_environments.py
        - mountPath: /etc/tower/conf.d/credentials.py
          name: awx-coopaname-application-credentials
          readOnly: true
          subPath: credentials.py
        - mountPath: /etc/tower/conf.d/ldap.py
          name: awx-coopaname-application-credentials
          readOnly: true
          subPath: ldap.py
        - mountPath: /etc/tower/SECRET_KEY
          name: awx-coopaname-secret-key
          readOnly: true
          subPath: SECRET_KEY
        - mountPath: /etc/tower/settings.py
          name: awx-coopaname-settings
          readOnly: true
          subPath: settings.py
        - mountPath: /var/run/redis
          name: awx-coopaname-redis-socket
        - mountPath: /var/run/supervisor
          name: supervisor-socket
        - mountPath: /var/run/awx-rsyslog
          name: rsyslog-socket
        - mountPath: /var/lib/awx/rsyslog
          name: rsyslog-dir
        - mountPath: /etc/receptor/receptor.conf
          name: awx-coopaname-receptor-config
          readOnly: true
          subPath: receptor.conf
        - mountPath: /var/run/receptor
          name: receptor-socket
        - mountPath: /var/lib/awx/projects
          name: awx-coopaname-projects
      - args:
        - receptor
        - --config
        - /etc/receptor/receptor.conf
        image: quay.io/ansible/awx-ee:latest
        imagePullPolicy: IfNotPresent
        name: awx-coopaname-ee
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/receptor/receptor.conf
          name: awx-coopaname-receptor-config
          readOnly: true
          subPath: receptor.conf
        - mountPath: /var/run/receptor
          name: receptor-socket
        - mountPath: /var/lib/awx/projects
          name: awx-coopaname-projects
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - chat.poleinfo.coopaname.coop
        ip: 10.0.255.2
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: awx-coopaname
      serviceAccountName: awx-coopaname
      terminationGracePeriodSeconds: 30
      volumes:
      - name: awx-coopaname-application-credentials
        secret:
          defaultMode: 420
          items:
          - key: credentials.py
            path: credentials.py
          - key: ldap.py
            path: ldap.py
          - key: execution_environments.py
            path: execution_environments.py
          secretName: awx-coopaname-app-credentials
      - name: awx-coopaname-secret-key
        secret:
          defaultMode: 420
          items:
          - key: secret_key
            path: SECRET_KEY
          secretName: awx-coopaname-secret-key
      - configMap:
          defaultMode: 420
          items:
          - key: settings
            path: settings.py
          name: awx-coopaname-awx-configmap
        name: awx-coopaname-settings
      - configMap:
          defaultMode: 420
          items:
          - key: nginx_conf
            path: nginx.conf
          name: awx-coopaname-awx-configmap
        name: awx-coopaname-nginx-conf
      - configMap:
          defaultMode: 420
          items:
          - key: redis_conf
            path: redis.conf
          name: awx-coopaname-awx-configmap
        name: awx-coopaname-redis-config
      - emptyDir: {}
        name: awx-coopaname-redis-socket
      - emptyDir: {}
        name: awx-coopaname-redis-data
      - emptyDir: {}
        name: supervisor-socket
      - emptyDir: {}
        name: rsyslog-socket
      - emptyDir: {}
        name: receptor-socket
      - emptyDir: {}
        name: rsyslog-dir
      - configMap:
          defaultMode: 420
          items:
          - key: receptor_conf
            path: receptor.conf
          name: awx-coopaname-awx-configmap
        name: awx-coopaname-receptor-config
      - emptyDir: {}
        name: awx-coopaname-projects
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-10-24T09:30:19Z"
    lastUpdateTime: "2021-10-24T09:30:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-10-24T07:16:34Z"
    lastUpdateTime: "2021-10-24T09:30:19Z"
    message: ReplicaSet "awx-coopaname-dd896cc5c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
